### ISSUE TITLE
 ce:GetCostAndUsage and support:DescribeCases missing 

### ISSUE THREAD

**Issue by rgarrigue** [mlabouardy/komiser#130]
Hi

Running 2.4.0 installed on my Ubuntu workstation with the `wget ...`. I'm having 2 notifications. I checked the policy (c/ced from the README link), the first ce:GetCostAndUsage exists, the support:DescribeCases should be taken care of by support:*.

I guess it's a side effect, the bill & bill forecast are 0.

**Comment by nida** [comment]
I have the same issue ? did you find a resolution @rgarrigue

**Comment by CyrilAll** [comment]
@mlabouardy is going to look into it :)

**Comment by wael-hamid** [comment]
Is there any new findings regarding this issue? I am running into this same problem. This happened to me when I started adding multiple accounts to test and between all of them they have admin access for now.

One account is working Ok but the others are giving me the error/warning about ce:GetCostAndUsage. I am suspecting that because these other accounts did not have the Cost Explorer enabled. From what I know you'd have to visit the Cost Explorer page on the console and wait for 24 hours for your data/history to start to populate so I will try again tomorrow and see if the behavior changes. Will report back with findings.

Thanks.

**Comment by CyrilAll** [comment]
Hello. OK thanks Wael, keep us informed :)

**Comment by kkashyap1707** [comment]
Please provide the correct role and then it will work.
