### ISSUE TITLE
Run multi aws account on ec2 with IAM role.

### ISSUE THREAD

**Issue by deepakkashyap2** [mlabouardy/komiser#188]
HI Team,

How can we run multi account komiser setup with IAM role on ec2.

**Comment by mlabouardy** [comment]
@deepakkashyap2 if you're running Komiser through the CLI, then unfortunately you can't since by default it uses the IAM role credentials. However, you can run Komiser through a Docker container and pass the a credentials file with multiple AWS accounts, see [here](https://github.com/mlabouardy/komiser#docker)
